### ISSUE TITLE
Allow transport listener to return multiple multiaddr

### ISSUE THREAD

**Issue by Jorropo** [libp2p/go-libp2p-core#70]
While working on the utp transport I was in trouble with the `Mutliaddr()` because I wasn't able to return multiple address if it was listening on `0.0.0.0`. So after a bit of testing I discovered returning a ma with ip `0.0.0.0` some how get transformed to mutliple address with the right interface.
But I don't think that a good solution because that highly specialized, lets say I do the same thing for an ethernet transport that would not works, yes I can still contrib to the package but I see 2 big issue with this :
 - That makes contributing to libp2p way harder than it should, the multiple repo system is quite confusing at first glance but it have some advantage such as repo are independent and you don't need to know how the whole project works to do your own muxer, transport or dht, you just have to expect them to works (that the real advantage of OOP). But if to make my transport working as expected I have to change other object this advantage its lost and there is no point to have an API system that complex, just one package libp2p with evrythings in it will do the work simply. (I know that a bad solution, this is just an example to show how libp2p does not agree with its principles on that, I don't expect somethings else to interfere with my transport (except maybe for nat traversal but in this case this is maybe better to have a layer below transport dedicated to that maybe with an `ListenAndForward(ma multiaddr.MultiAddr) (net.Listener, error) // only accept thinwaist maddr` function)).
- That not plug and play, I don't think all transport in the future are gonna be official libp2p transport, if someone makes an morse code transport he should be limited just because that not very usefull and his transport should integrate as well as official transport (just using `libp2p.Transport(fancyButQuiteUselessTransport.New)`) and not using a fork of libp2p made to be compatible with this transport.

I personaly think here straigh forward is better here, just change `Multiaddr() ma.Multiaddr` to `Multiaddr() []ma.Multiaddr`.
But that not retroincompatible ? No, we can easly create 2 wrapper, one for the Transport object (with direct call to the underlying function of the real transport except for Listen wich just return an wrapped Listener object) and one for Listener (with again direct call to all the underlying function of the real listener function except for `Multiaddr` wich return the original multi addr in a list (and do the transformation of `0.0.0.0` to the real address if needed)).
And wrapping older transport in `libp2p.Transport` to the newer one.

Obviously that just a discussion but I really think we need to be able to some how return multiple maddr from one listener, how to do it isn't very import (we can also maybe call `listener.Multiaddr()` multiple times, returning a new maddr each time, cycling beetween all possible and stopping when 2 duplicates are found (2 duplicates just indicate we have looped over the list and for older transport with just 1 maddr they will allways return the same wich is like having an list with a len of 1)).

**Comment by raulk** [comment]
Hey @Jorropo! Thanks for spearheading the work in getting the uTP transport up and running with the latests versions of go-libp2p. Very much appreciated!

The multirepo vs. monorepo discussion does crop up frequently. We continuously take steps toward a more cohesive DX; namely in the last months we consolidated interfaces into `go-libp2p-core` from 12+ repos. Now we're consolidating issue tracking into the top-level go-libp2p repo.

Re: the concrete issue here, we can't make transports resolve "bind all" and magic addresses, because that's the wrong layer and that would leak concerns. In other words, we'd be making the OSI layer 4 deal with concerns of OSI layer 3.

That's why there's this inversion of control in place. Transports listen on a single logical address, which when resolving it may unpack into several physical addresses.

If you genuinely want a transport to listen on multiple logical addresses, you'd instantiate that transport more than once, each with a different listen address.

Would you mind explaining how the current handling of _bind all_ addresses is causing trouble in go-libp2p-utp-transport?

**Comment by Jorropo** [comment]
@raulk currently there is none in go-utp-transport, returning `/ip4/0.0.0.0/udp/<port>/utp` works well and get resolved, I have a problem with the i2p-sam transport I want to make after the utp one.

The problem is i2p have 2 way to encode address, garlic32 and garlic64 (the first one is a hash of the second, to use it you will have to do a lookup in the i2p dht).
So yes in this case we can do the same things, we do with ip and return garlic64 and resolving later elsewhere to get the garlic32 version, but that not plug and play and I don't think i2p is gonna be only case requiring that and I think its better to just let transports manage that by them self to be more future proof (or maybe not for special known case (such as ip or ether)).
